### ISSUE TITLE
Form values are empty

### ISSUE THREAD

**Issue by akoenig** [renatorib/react-powerplug#102]
First of all: Thanks, @renatorib for building `react-powerplug`. It is a masterpiece!

I found a tricky scenario when using `powerplug` with [react-adopt](https://github.com/pedronauck/react-adopt) though. Curious to hear your thoughts on this. Not sure if this is really a bug. Consider the following example:

```js
import React from "react";
import { render } from "react-dom";

import { adopt } from "react-adopt";
import { Form } from "react-powerplug";

const Container = adopt({
  form: <Form initial={{ username: "", password: "" }} />
});

const App = () => (
  <Container>
    {({ form }) => {
      return (
        <form
          onSubmit={e => {
            e.preventDefault();

            console.log(form.input("username").value);
            console.log(form.input("password").value);

            console.log("----");
            console.log(form.values);
          }}
        >
          <p>
            username
            <input type="text" {...form.input("username").bind} />
          </p>
          <p>
            password
            <input type="password" {...form.input("password").bind} />
          </p>

          <button type="submit">Login</button>
        </form>
      );
    }}
  </Container>
);

render(<App />, document.getElementById("root"));
```

The `console.log(form.values);` is always `undefined`, whereas printing the inputs separately works like a charm.

**Comment by renatorib** [comment]
Hey @akoenig, thanks for your compliments :)

I suspect you're using version `0.1.x` of powerplug, that does not have `values` api. Form `values` was added in `1.0` (master branch) which is in the alpha phase (1.0.0-alpha.4)

**Comment by akoenig** [comment]
@renatorib Autsch, true story, my fault :) Closing here.

**Comment by renatorib** [comment]
No problem! Actually It's our fault. People always get confused (#84, #85) and I'm not exactly sure how to improve this communication
