### ISSUE TITLE
Nested properties in Form

### ISSUE THREAD

**Issue by alexkrolick** [renatorib/react-powerplug#133]
It would be cool if form elements could bind to values like `user.name`, similar to https://github.com/developit/linkstate#how-it-works

I might take this on if it sounds like an API you'd want

**Comment by TrySound** [comment]
@alexkrolick How's it different from spreading `.bind`?

**Comment by alexkrolick** [comment]
if the form value is ```js
{
  user: {
    name: 'I am a nested value' 
  }
}
```

**Comment by TrySound** [comment]
Could you provide and example how this api could look like?

**Comment by alexkrolick** [comment]
```js
<Form initial={{ subject: '', message: '', user: { name: '', email: '' } }}>
  {({ input, values }) => (
    <form
      onSubmit={e => {
        e.preventDefault()
        console.log(values)
      }}
    >
      <ControlledInput placeholder="To: (email)" {...input('user.email').bind} />
      <ControlledInput placeholder="To: (name)" {...input('user.name').bind} />
      <ControlledInput placeholder="Subject" {...input('subject').bind} />
      <ControlledTextArea placeholder="Message" {...input('message').bind} />
      <Submit>Send</Submit>
    </form>
  )}
</Form>
```

**Comment by TrySound** [comment]
I wouldn't like to add path getters to powerplug api. They are not statically analyzable in ts/flow. We already have dead (for me) `compose` helper. Type safety is important criteria for this project.

**Comment by renatorib** [comment]
Hey @alexkrolick, it solves your problem? I can close the issue?

**Comment by alexkrolick** [comment]
Yeah I'll just go with that. Might be worth documenting that approach as an example since it enables a lot more complex forms to be built.

**Comment by renatorib** [comment]
Sounds good!
