### ISSUE TITLE
[Feature Request] Integrate with HOCs.

### ISSUE THREAD

**Issue by rockmandash** [renatorib/react-powerplug#135]
Hello, first of all, thank you for this wonderful library.
This library and **react-fns** are my **favorite** librarys!
However, it's often to run into some situations that you need to access some property in lifecycle hoods that react-powerplug provides you.
If we can have HOC, the code will become much nicer like this.
```javascript
export default withToggle(MyApp)
```
Thank you!

**Comment by TrySound** [comment]
Just wrap with component. This will prevent you from props pollution/overriding and will provide you type safety.
```js
import { Toggle } from 'react-powerplug';

const InnerApp = () => null

const App = () => (
  <Toggle>
    {checkbox =>
      <Toggle>
        {modal =>
          <InnerApp checkbox={checkbox} modal={modal} />
        }
      </Toggle>
    }
  </Toggle>
)
```

**Comment by rockmandash** [comment]
Thank you for your fast reply!
Yes, HOC can't do the example you provide.
Learned a lesson!
