### ISSUE TITLE
webpack doesn't seem to be able to tree-shake the rollup bundle, I analyzed some webpack builds...

### ISSUE THREAD

**Issue by jedwards1211** [renatorib/react-powerplug#142]
I think we need to do some more investigation of this.  I profiled my webpack production build after adding the following single import:

```js
import {Toggle} from 'react-powerplug'
```

As seen in the webpack analyze tool, All 22 KiB of `react-powerplug` got bundled up:  (**EDIT**: I need to check if this is actually the size of the code in the bundle or just the input file size.  It's not clear from the webpack analyze tool...)

![image](https://user-images.githubusercontent.com/1448194/43109281-9d4d3c64-8eab-11e8-9350-fd7c917f36b4.png)

Then I added `"sideEffects": false` to `node_modules/react-powerplug/package.json`, reran the build, and analyzed again.  The result?  Unfortunately, still 22 KiB.

Also, while trying to see if I could successfully tree shake version 0.1.6 instead, I noticed that the `es/` directory contained commonjs exports, which I thought defeats the purpose of having a separate `es/` directory?

**Comment by TrySound** [comment]
Just create local project with
```js
// webpack.config.js
```

**Comment by TrySound** [comment]
Just create small project with
```js
// webpack.config.js
module.exports = {
  mode: 'production',
  externals: {
    'react': 'React'
  }
}
// src/index.js
import { Toggle } from 'react-powerplug';
console.log(Toggle)
```

run webpack and then prettier on dist. You won't find there `list` of `focus` words which exist in powerplug.

**Comment by TrySound** [comment]
Just don't use broken services. Check by yourself. It's simple.

**Comment by jedwards1211** [comment]
The screenshot from `webpack.github.io` is just from their analyze tool which shows results from the output of `webpack --stats --json` that I ran locally on my machine with webpack 4.12.0.

I opened this issue to soon, I'll do more digging in my own build and try to figure out what my issue is.
