### ISSUE TITLE
[Feature Request] <Tabs /> component for Tabs or Carousel.

### ISSUE THREAD

**Issue by rockmandash** [renatorib/react-powerplug#143]
Hello, first, thank you for this wonderful library!
I want to ask if we can have a <Tabs /> component for Tabs or Carousel usage.
For example:
```javascript
<Tabs items={['A', 'B', 'C']} infinite>
{
  ({currentTab, inc, dec}) => {
    return (
      <div className='some tabs or carousel'>
        Current position is ${currentTab}
      </div>
    )
  }
}
</Tabs>
```
Infinite prop is if I am in C, and I trigger inc(), I will be A.
Thank you!

**Comment by TrySound** [comment]
This logic is usually encapsulated inside tabs and inside carousels. It can be quite specific. This lib is more about state management and dom interaction than ui stuff. This logic is not so hard to write by hands and then add own nice features
```js
const list = ['A', 'B', 'C']
const Component = () => (
  <plug.Value initial={0}>
    {position => {
      const inc = () => position.value === list.length - 1 ? 0 : position.value + 1;
      const dec = () => position.value === 0 ? list.length - 1 : position.value - 1;
      return (
        <div className='some tabs or carousel'>
          Current position is ${position.value}
        </div>
      )
    }}
  </plug.Value>
)
```

**Comment by rockmandash** [comment]
Wow, thank you for showing me this trick!
