### ISSUE TITLE
Warning: The prop `children` is marked as required

### ISSUE THREAD

**Issue by sandiiarov** [renatorib/react-powerplug#147]
When I try to compose components with `PropTypes.children.isRequired` then I see this annoying warning.

<img width="885" alt="screen shot 2018-08-05 at 8 36 36 pm" src="https://user-images.githubusercontent.com/15861257/43692706-4b189d46-98ef-11e8-8130-71ca8071a499.png">

The temporary solution is not looking good:
```js
<Compose
    components={[
        <Query query={QUERY} children={() => {}} />,
        <Mutation mutation={MUTATION} children={() => {}} />,
    ]}
>
```

**Comment by renatorib** [comment]
Please read https://github.com/renatorib/react-powerplug/issues/183#issuecomment-433090312
