### ISSUE TITLE
Individual imports

### ISSUE THREAD

**Issue by souporserious** [renatorib/react-powerplug#15]
First, great job on everything! I love all of these small, powerful components 🙌. I was curious.. since I only need a subset of these, is it possible to set up the build so we can do imports like this:
```js
import Hover from 'react-powerplug/Hover'
```

I'm not too familiar with rollup, but I can try out a PR if you would like 😁

**Comment by renatorib** [comment]
Thanks again :smile: 

For now it's possible to import this way
```js
import Hover from 'react-powerplug/lib/components/Hover`
``` 
or
```js
import Hover from 'react-powerplug/es/components/Hover`
``` 

(I don't know the difference :sweat_smile:)

**Comment by souporserious** [comment]
Oh awesome! That's wonderful 👏  I'll look into it and see if we can make them a litter easier to write, but this works great for now. Thanks for the quick reply!

**Comment by renatorib** [comment]
You're welcome! 

I will leave this issue open, so anyone can help too.

**Comment by TrySound** [comment]
I would not rely on folder structure. It's bad pattern and tree shaking improvements in the last months can prevent us from it.

**Comment by renatorib** [comment]
You are right @TrySound.
Do you have some suggestions?

**Comment by TrySound** [comment]
I tried both rollup and webpack and they both treeshake good. The only side effect now is `State` component, but it's base component, it always will be if library is used.

**Comment by TrySound** [comment]
`State` treeshaking will be available after https://github.com/babel/babel/pull/6963 merge

**Comment by Andarist** [comment]
I can only confirm that generally speaking flat bundling (what rollup does) is better than having a directory structure - it allows for easier tree-shakeability webpack (upcoming webpack@4 might get better at this, but anyway many, many users still use webpack 2 or 3). 

There is no reason to allow for `package/submodule` imports (also setting this up in proper way is quite difficult and there is no tool - that im aware of - at the moment which does it automatically). I see a room for `package/flavour` though (i.e. `unistore/react`, `unistore/preact`), but this library is a set of utilities and as such IMHO it should be accessible from a single entry point.

Having a proper tree-shaking tooling will make proposed `import Hover from 'react-powerplug/Hover'` and `import { Hover } from 'react-powerplug` equivalent - exact same code should land in your final bundle.

**Comment by renatorib** [comment]
Thanks @Andarist!

I'll close this since v1 will not have a export default (https://github.com/renatorib/react-powerplug/pull/31), which will help with tree shaking.
