### ISSUE TITLE
State component - "onChange" question

### ISSUE THREAD

**Issue by yairEO** [renatorib/react-powerplug#170]
https://github.com/renatorib/react-powerplug/blob/master/docs/components/State.md

( I would like to point out that the README above lack an example for `onChange`)

My question is, is it possible to have `onChange` listen to a very specific Boolean in my state and only when that Boolean changes, fire the `onChange` callback?

I don't want to execute the `onChange` on every state change but for a very specific item in the state.
seems better for performance in my scenario.

**Comment by renatorib** [comment]
Unfortunately its not possible. What you can do is check the onChange's response and perform the action only if the specific value you want has changed. But onChange will fire whenever any value changes, this can not be avoided for now. Sorry.
