### ISSUE TITLE
Latest should not point to a release candidate

### ISSUE THREAD

**Issue by stam** [renatorib/react-powerplug#173]
`yarn info react-powerplug` lists:

```
{ name:
   'react-powerplug',
  description:
   'Give life to your dumb components',
  'dist-tags':
   { next:
      '1.0.0-rc.0',
     latest:
      '1.0.0-rc.1' },
...etc
```

It is weird that next > latest. Also, latest should point to a stable release.
It should be:
```
'dist-tags': { latest '0.1.6', rc: '1.0.0-rc.1' }
```

**Comment by renatorib** [comment]
I don't know much about tags. @TrySound can you help?

**Comment by TrySound** [comment]
@stam You are right. My fault. @renatorib tag release is `npm version patch && npm publish --next`. We need to publish new versions.

**Comment by stam** [comment]
Is there anything I can do to help with this?

**Comment by TrySound** [comment]
@stam We are gonna publish 1.0 soon.

**Comment by renatorib** [comment]
now latest is 1.0.0
thanks
