### ISSUE TITLE
Rename some component in 1.0

### ISSUE THREAD

**Issue by TrySound** [renatorib/react-powerplug#18]
- `Set` conflicts with native one
- `State` AFAIK is used often with typescript and flow for state type (it's still may be required for State component `initial`).

It's just a note to consideration.

**Comment by renatorib** [comment]
Nice points! BTW, Set and Map are two components that I'm considering to include in 1.0 too. 

I need to think in a name to the current Set component that works as "key-value" setter/getter. I'm really bad with names.

**Comment by alexkrolick** [comment]
> "key-value" setter/getter

How about `Store` or `KeyValue`?

**Comment by TrySound** [comment]
Also maybe we can choose some suffix? Implementing `Toggle` can be not easy with the same component in the scope. Something like `SetPlug`, `StatePlug`, `TogglePlug`?

**Comment by TrySound** [comment]
Suffix is good to associate usage with native stuff, but without name collision.

**Comment by renatorib** [comment]
I don't like suffix, but I know this could be a problem.

**Comment by TrySound** [comment]
I have thought a bit more. This is really unnecessary. I always forget about namespaces in esm, which are exists for such cases.
```js
import * as React from 'react'
import * as plug from 'react-powerplug'

const A = () => <plug.State />
const B = () => <plug.Set />
const C = () => <plug.Map />
```
