### ISSUE TITLE
`State` component implements `Value` component & not the other way around

### ISSUE THREAD

**Issue by harrysolovay** [renatorib/react-powerplug#180]
Hi,

I have a question about the component hierarchy: Why is it that the `State` component is using the `Value` component? It appears `Value` implements setState within its `_set` method, which scopes it to the state's `value` member. Then, the `State` component is wrapped with `Value`, which implements a new setState that calls the _set passed from `Value`... this means that setState/_set is unnecessarily implemented twice... also, the `State` component scopes setState to `value` (internally), which isn't necessary (might as well use the built-in setState). Also, there's an extra container in the mix. Please let me know if there was some other thinking behind this... I don't mean to sound critical... I'm just looking for opportunities to contribute to this library. I really dig the render-props pattern & wanna improve/add to this lib with features more geared toward global state management.

Please let me know your thoughts & thanks for looking this over.

Kind regards,

Harry

**Comment by TrySound** [comment]
@harrysolovay It's because of `reset` function. It's not possible to implement reset for "native" `setState` because it's always extended, not overridden.

**Comment by harrysolovay** [comment]
Ahhh, I see. That makes a lot of sense. Thank you 👍

**Comment by renatorib** [comment]
It may not seem like it, but it simplifies a lot as well! Look https://github.com/renatorib/react-powerplug/pull/149
