### ISSUE TITLE
Wrong types with Flow and react-composer and compose

### ISSUE THREAD

**Issue by FezVrasta** [renatorib/react-powerplug#183]
If I do this:

```jsx
<Composer
  components={[
    <Value key="test" initial={true} />,
  ]}
>
```

I get:

```
[flow] Cannot create `Value` element because: Either property `render` is missing in props [1] but exists in object type [2]. Or property `children` is missing in props [1] but exists in object type [3]. (References: [1] [2] [3])
```

if I do the same with other render-props components such as react-apollo's `Query`, it works just fine.

Is there any chance to see this fixed?

edit: actually it happens even with the react-powerplug Compose utility

**Comment by TrySound** [comment]
Render and children cannot be optional. Composability with type inference doesn't work yet.
You may compose however you want without doubtful utilities.
```js
const Composed = ({ children }) => (
  <Value>
    {dialog =>
      <Value>
      </Value>
    }
  </Value>
)
<Composer
  components={[
    () => <Value key="test" initial={true} />,
  ]}
>
```
