### ISSUE TITLE
"renderless" in description confusing

### ISSUE THREAD

**Issue by TrySound** [renatorib/react-powerplug#19]
Where did it come from? [react docs](https://reactjs.org/docs/render-props.html) refers to it as render props.

"renderless" is something which does not affect render. But state containers are embedded to render, so it's weird IMHO.

**Comment by renatorib** [comment]
I think **renderless** is a good name and fits the purpose. The entire lib does not render any DOM element. It provides only data so you can render with your own UI. But this UI is not powerplug anymore. 

I know that the "winner term" is render props, and I think I can refer this more than once in docs to avoid confusion, but personally I want to call powerplug as Renderless Components.

**Comment by alexkrolick** [comment]
Me too :P https://github.com/alexkrolick/react-renderless

I haven't worked on my lib nearly as much as @renatorib but they both came out at the same time and are inspired by the same concept. Here's how I explain it in the readme:

> A renderless component is the opposite of a stateless component. It does not implement a render method. Instead, renderless components are composed with stateless functional components to create UI elements.
