### ISSUE TITLE
rename inc -> increment, dec -> decrement

### ISSUE THREAD

**Issue by souporserious** [renatorib/react-powerplug#34]
Since we're breaking API's before 1.0 😇  how would you feel about renaming `inc` to `increment` and `dec` to `decrement` since the pattern of the other components all use full names? For example, `value` instead of `val`. I can submit a PR for this if you are on board, please let me know.

**Comment by renatorib** [comment]
I like `inc` and `dec`... Maybe we can use it as an alias, what do you think?

`increment` and `decrement` as 'official' and `inc` and `dec` as alias

**Comment by souporserious** [comment]
No worries! `inc` and `dec` are fine. I'd rather have only one way to do it.
