### ISSUE TITLE
Mobile support on *Active* and *Hover* component

### ISSUE THREAD

**Issue by farskid** [renatorib/react-powerplug#39]
For now, the `Active` component simulates active state on any HTML element by using `onMouseUp` and `onMouseDown` and `Hover` component uses `omMouseEnter` and `onMouseLeave` events.

The issue is on mobile devices. Mobile devices can control and simulate those behaviors by using events such `ontouchstart` and `ontouchend`. Right now, these components don't work on mobile devices.

I'd like to contribute and add the behavior if you're looking into supporting mobile devices too. will be happy to send a PR for it.

**Comment by souporserious** [comment]
Sounds good 👍 If this is added, I think it should be toggleable in some way. It's nice to have an option of not having hover triggered on mobile. Maybe even a `Touch` component with touch event info? Then they can be composed together to make a `HoverTouch` component or whatever.

**Comment by renatorib** [comment]
We will be happy to improve powerplug. Feel free to send PR!

**Comment by farskid** [comment]
@souporserious @renatorib I like the idea of having a `Touch` component and compose it with `Hover`. I'll be working on a prototype of it and will discuss more when sent the first PR version. sounds good?

**Comment by farskid** [comment]
@souporserious @renatorib I've created a component as @souporserious suggested. The idea of composing it with any other component sounds cool to me. Maybe we can discuss the ability to configure hover state on mobile?

**Comment by renatorib** [comment]
Done
