### ISSUE TITLE
Composing two of the same kind

### ISSUE THREAD

**Issue by gnapse** [renatorib/react-powerplug#47]
I realized this when trying to replace [my own render props composer](https://codesandbox.io/s/04w609rvz0) with the one in this library.

Imagine the following scenario:

```js
<Toggle initial={true}>
  {outer => (
    <Toggle initial={false}>
      {inner => (
        <Checkbox checked={outer.on} onChange={outer.toggle} />
        <Checkbox checked={inner.on} onChange={inner.toggle} />
      )}
    </Toggle>
  )}
</Toggle>
```

Given that `Compose` uses the name of the component to build the props, I'm not sure if this is possible to compose.

```js
<Compose
  states={[
    <Toggle initial={true} />,
    <Toggle initial={false} />,
  ]}
>
  // The line below shows the problem, we have a name clash in the prop names
  {({ toggle, toggle }) => (
    <Checkbox checked={toggle.on} onChange={toggle.toggle} />
    <Checkbox checked={toggle.on} onChange={toggle.toggle} />
  )}
</Compose>
```

If `Composed` passed the different props of the composed components as positional arguments to the unified render prop function, this would be solved:

```js
<Compose
  states={[
    <Toggle initial={true} />,
    <Toggle initial={false} />,
  ]}
>
  {(outer, inner) => (
    <Checkbox checked={outer.on} onChange={outer.toggle} />
    <Checkbox checked={inner.on} onChange={inner.toggle} />
  )}
</Compose>
```

If you think about it, it makes more sense, if you provide a sequence of components to be composed, that you get the corresponding sequence of props that each of them provide, instead of an object of props.

If you agree I'm more than happy to make a PR myself.

**Comment by souporserious** [comment]
Love this idea! I just saw something similar from James Kyle this morning https://twitter.com/thejameskyle/status/958683451078590465

![image](https://user-images.githubusercontent.com/2762082/35649180-148b5e52-068d-11e8-8bf6-b39923a2e663.png)

**Comment by renatorib** [comment]
Yea, I like it. I already had this idea in my head for 1.0. I think it's the best way to compose without conflicts.

**Comment by gnapse** [comment]
Do you want me to work on a PR? I already implemented this exact same functionality in the library I was using internally for this: https://github.com/gnapse/render-props-compose

**Comment by renatorib** [comment]
If you want, feel free to send a PR! 😄

**Comment by gnapse** [comment]
@renatorib can you explain to me what this phrase in the README means? I'm a bit lost about it:

> Because of that, when you use toggle function, only `<Toggle>` will be rerendered, but if you use inc or dec functions, both `<Counter>` and `<Toggle>` will be rerendered. Even using `compose() utility`.

It's at the end of the section of the README that talks about the composed components.

**Comment by renatorib** [comment]
With `compose` function, when you do that
```js
const ToggleCounter = compose(Toggle, Counter)

<ToggleCounter>
  {({ toggle, counter }) => (
    <div>...</div>
  )}
</ToggleCounter>
```

Is the same as doing this:
```js
<Counter>
  {counter => (
    <Toggle>
      {toggle => (
         <div>...</div>
      )}
    </Toggle>
  )}
</Counter>
```

When Toggle state is changed, only Toggle component will rerendered.
But when Counter stated is changed, all inside it will be rerendered: Counter and Toggle.

Is nothing problematic or dangerous, it's just to document the behavior

**Comment by gnapse** [comment]
Thanks, yeah, I had misread it a bit and hence I did not fully understand it.

PR submitted BTW, let me know how it's looking when you get the chance.

**Comment by renatorib** [comment]
Sure! 😄 

If you want to see it in action: https://stackblitz.com/edit/react-pe1ye3
Open console and click toggle button, after click counter button, and see the logs

I'll see your PR soon, thanks!
