### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by renatorib** [renatorib/react-powerplug#5]

**Comment by yakovlevyuri** [comment]
@renatorib Hey, can help you to add Storybook to the project and Jest tests.

**Comment by renatorib** [comment]
@yakovlevyuri That will be great! Feel free :D

**Comment by renatorib** [comment]
Added some initial tests with jest/enzyme. But nothing very expressive, just testing it's mouting. I do not have much testing experience, so I'm going to need some help for sure.

I'll create another issue to improve tests
