### ISSUE TITLE
Compose using component names? What about uglify?

### ISSUE THREAD

**Issue by kentcdodds** [renatorib/react-powerplug#52]
Am I missing something? I feel like when components are uglified, their names will be changed and my compose will be broken... Shouldn't it instead be array position? Or I should name my components explicitely?

Either:

```javascript
const ToggleCounter = compose(Toggle, Counter)

<ToggleCounter>{([toggle, counter]) => <div />}</ToggleCounter>
```

Or

```javascript
const ToggleCounter = compose({toggle: Toggle, counter: Counter})

<ToggleCounter>{({toggle, counter}) => <div />}</ToggleCounter>
```

Otherwise uglify is going to break this.

**Comment by aulisius** [comment]
In the [compose util](https://github.com/renatorib/react-powerplug/blob/master/src/utils/compose.js#L20),

This
```jsx
const renderFn = props =>
       isTheLast
         ? renderProps(composedProps, { [name(element)]: props, ...stacked })
         : stackProps(i - 1, elements, { [name(element)]: props, ...stacked })
```

could be written as 
```jsx
const renderFn = props =>
       isTheLast
         ? renderProps(composedProps, [props, ...stacked])
         : stackProps(i - 1, elements, [props, ...stacked]) // Also start from 0 instead of from last
```

This would preserve order and not depend on `Component.displayName`

**Comment by renatorib** [comment]
It will be changed in #51. Master branch is unstable/development. Current stable version (0.1) don't use component names

**Comment by gnapse** [comment]
BTW, it could support both positional arguments (as provided by #51) but it can also support named arguments, just not deriving the names from the components. I developed both capabilities in [render-props-compose](https://github.com/gnapse/render-props-compose).

I can try to re-create that approach here too, in #51.

**Comment by renatorib** [comment]
I think it's best to keep only one.  IMHO, by array is the best solution

**Comment by gnapse** [comment]
Yup, IMO that's the best option too.
