### ISSUE TITLE
ShouldUpdate

### ISSUE THREAD

**Issue by souporserious** [renatorib/react-powerplug#56]
Do you think it would be beneficial to have a `ShouldUpdate` component? 🤔

I was reading through [these docs](https://github.com/atlassian/react-beautiful-dnd#recommended-droppable-performance-optimisation) and it seemed like it could be nice to have.

Not sure how this would even work. But could maybe look something like:
```jsx
<ShouldUpdate
  when={(currentProps, nextProps) =>
    currentProps.students !== nextProps.students
  }
>
  // only update sometimes
</ShouldUpdate>
```

Might be better to just make another component honestly 😅 curious to hear your thoughts.

**Comment by streamich** [comment]
This sounds interesting, because this way you the `when` function is dynamic, it can use any variables from the render method scope.

**Comment by TrySound** [comment]
Just don't add lifecycles here. Such components will introduce a lot of mess and issue because everybody can use variables from scope. It's a kind of reacting programming, which is much harder and do not related to react. So let's just use class here.

**Comment by streamich** [comment]
The whole `powerplug` repo is about inverting `.setState()`, maybe the proposed `<ShouldUpdate>` does not fit into this repo as it inverts a life-cycle method, but fundamentally I don't see a problem with it.

I actually even like this idea and thinking about adding it to my [inversion list](https://github.com/MailOnline/libreact/blob/master/docs/en/Inversion.md) right now.

**Comment by TrySound** [comment]
It doesn't fit to react in a way you want. It's not possible to implement it good without internal react support.

**Comment by streamich** [comment]
In fact it is just a generalization of `pure()` HOC. Because you of `<ShouldUpdate>` FaCC you create `shouldUpdate()` HOC:

```js
const shouldUpdate = (when) => (Comp) => (props) =>
  h(ShouldUpdate, {when, props}, h(Comp, props));
```

And then you use that to create `pure()` HOC:

```js
const pure = shouldUpdate((a, b) => !shallowEqual(a, b));
```

**Comment by renatorib** [comment]
Hey @souporserious 

As I said here #41 and here #43,

I like the idea of utilities to control lifecycles.
In fact, the powerplug was born of a need to simplify things. In the same way that I can facilitate state creation without having to create a class component, it would be interesting to facilitate the creation of these lifecycles quickly. I really appreciate the idea.

However, I think it goes against the initial idea of the project: abstract **states** and send via **render props**. The other day I was thinking about how I could fit components like this into the powerplug. Maybe if there was any clear separation between what is "State Containers" and what is "Lifecycles Containers (??)" (I hate naming things).

If we can make this separation of concerns, I think maybe we can start to include this kind of utility, as well as the Mouting utility of TrySound #43 

What is your opinion, guys?

**Comment by streamich** [comment]
Just call it:

- State Inversion
- Lifecycle Inversion
- Ref Inversion

**Comment by souporserious** [comment]
[Looks like this has been done by Ryan Florence](https://github.com/ryanflorence/react-component-component) :). I'd rather just use a class now the more I think about it 🤷‍♂️
