### ISSUE TITLE
Compose refs helper

### ISSUE THREAD

**Issue by souporserious** [renatorib/react-powerplug#57]
I was curious if you had any ideas about some type of utility to help with composing multiple ref functions that could possibly be added to this library? I'm thinking it would be similar to the `composeEvents` function we talked about in https://github.com/renatorib/react-powerplug/issues/32.

I'm wondering if there is any way to memoize all the function calls so we can [avoid this caveat](https://reactjs.org/docs/refs-and-the-dom.html#caveats) when composing multiple refs? It would be really cool if this could be baked into `composeEvents` as well.

This is my idea:
```js
function memoize(fn) {
  memoize.cache = {}
  return function() {
    var key = JSON.stringify(arguments)
    if (memoize.cache[key]) {
      return memoize.cache[key]
    } else {
      var val = fn.apply(this, arguments)
      memoize.cache[key] = val
      return val
    }
  }
}

function memoizeRefs(...fns) {
  return node => {
    fns.forEach(fn => memoize(fn))
  }
}
```

**Comment by streamich** [comment]
Maybe `React.createRef()` could help?

**Comment by TrySound** [comment]
@streamich `createRef` is dead simple and not composable.

**Comment by TrySound** [comment]
https://github.com/reactjs/rfcs/pull/30#issuecomment-373577382

**Comment by renatorib** [comment]
I think `composeEvents` (#71) can handle multiple refs as well.

``` jsx
const handleRef1 = (ref) => console.log(1, ref)
const handleRef2 = (ref) => console.log(2, ref)

<div {...composeEvents({ ref: handleRef1 }, { ref: handleRef2 })}>
  Ref div
</div>
```

If someone wants to contribute a caveat solution say here that I reopen this issue. :v:

**Comment by souporserious** [comment]
Nice! Looks like it's working great [here](https://codesandbox.io/s/4850kr7vjx) 🤘. Wonder if `composeProps` might be a better name since it can apply to more than events, thoughts? 🤔
