### ISSUE TITLE
Discussion for 1.0

### ISSUE THREAD

**Issue by renatorib** [renatorib/react-powerplug#6]
1.x will be a fully breaking change in 0.x api, and that's why I'm planning on version 1.0 so early. 

**I'm open to all suggestions, opinions, considerations, etc.**

### Components and their Children Props
```
State
  state
  setState

Toggle
  on
  toggle
  set

Counter
  count
  inc
  dec
  incBy
  decBy
  set

List
  list
  push
  remove
  filter
  sort
  set

Map (KeyValue?)
  values
  set
  get

Set
  values
  add
  clear
  remove
  has

Value
  value
  set

Input
  bind
  value
  set
  
Form
  input(key)
    bind
    value
    set

Hover
  isHover
  bind

Active
  isActived
  bind

Focus
  isFocused
  bind

Touch
  isTouched
  bind

Compose
```

### Set Methods
All set methods will be the "set or over pattern" (I don't know if this pattern have a name), same as setState: If pass plain value, set the value, if pass function, evaluate with actual value and set the value. 

```ts
function set(value: ValueType | ((value: ValueType) => ValueType): void
```
```js
set(15)  // raw set
set(value => value + 5) // set using prev value
```

Example:
```jsx
<Value initial={1}>
  {({ value, set }) => (
    <div>
       Your value is: {value}<br />
       <button onClick={() => set(0)}>Reset</button>
       <button onClick={() => set(10)}>Set value to 10</button>
       <button onClick={() => set(v => v + 10)}>Add 10</button>
    </div>
  )}
</Value>
```

### Compose
Compose function will wrap the component methods/properties in a object with their lowercase name. It avoids naming conflicts like `set`, `value`, etc. Example:

```js
const CounterToggle = compose(Toggle, Counter)
```
Before (0.x):
```jsx
<CounterToggle>
  {({ count, inc, dec, toggle, on }) => (
    <div onClick={inc}>...</div>
  )}
</CounterToggle>
```
After (1.x):
```jsx
<CounterToggle>
  {({ counter, toggle }) => (
    <div onClick={counter.inc}>...</div>
  )}
</CounterToggle>
```

### Mouse/Scroll components.

Already started in prototype. I've plan to add these both 'trackers'

### Tests
> added some simple tests in 0.1.x

Yes, add tests. Tests are important.

### TypeScript / Flow Definitions 
> added flow types by @TrySound in 0.1.x

Add typings.

### Preact Interop

I need to study how can I make this interop, but it's on my mind. Not a hight priority.

### Website & Docs

Gatsby? Maybe. Need to think about.

**Comment by renatorib** [comment]
Thinking about components like `<Hover>` that binds onMouseEnter / onMouseLeave

```jsx
<Hover>
  {({ isHovering }) => (
    <div>{isHovering ? 'Hovering' : 'Not hovering'}</div>
  )}
</Hover>
```

But can't think in more cases like that to include

**Comment by renatorib** [comment]
Thinking about support `render prop`:

```jsx
<Counter render={({ inc, dec, count }) => (
  <div>...</div>
)} />
```

**Comment by renatorib** [comment]
Support for render prop and some other components will be added in 0.4.0 https://github.com/renatorib/react-powerplug/pull/7

**Comment by renatorib** [comment]
Adding already adding initial jest/enzyme tests in 0.4.

**Comment by TrySound** [comment]
bindedValue -> boundValue
setBindedValue -> setBoundValue

**Comment by renatorib** [comment]
damn irregular verbs

**Comment by TrySound** [comment]
@renatorib What is not done for 1.0? It's a bit frustrating to not use all new features we added.

**Comment by TrySound** [comment]
@renatorib Congrats with 1000 stars!

**Comment by renatorib** [comment]
@TrySound thanks! Congrats for us.
I published an alpha version ` react-powerplug 1.0.0-alpha.2 published 🎉` so we can use it while it's not 100% finished

**Comment by TrySound** [comment]
There was alpha 1?:)

**Comment by renatorib** [comment]
mistake :p

**Comment by ianstormtaylor** [comment]
@renatorib any idea when `1.0` will land? This library is really nice 😄 thank you!

**Comment by TrySound** [comment]
Soon. The latest breaking change is under review

**Comment by TrySound** [comment]
I'm thinking about is* fields. Most of the time I see in a code it's used as a function name. So the current choice may be confusing. What do you think if we will make one more breaking change with this renaming?

isActive -> active
isFocused -> focused or focusing
isHovered -> hovered
isTouched -> touched

For the same reason we don't call Toggle `on` as `isOn`

**Comment by TrySound** [comment]
@renatorib what do you think?

**Comment by renatorib** [comment]
I think its better! We can change it

**Comment by TrySound** [comment]
I think the API is stable now. @renatorib let's release `rc.0`?

**Comment by renatorib** [comment]
Nice

**Comment by xialvjun** [comment]
more complete `Form`?

```jsx
import * as React from 'react'
import State from './State'
import renderProps from '../utils/renderProps'
import set from '../utils/set'

const Form = ({ initial = {}, onChange, ...props }) => (
  <State initial={{ ...initial }} onChange={onChange}>
    {({ state, setState }) =>
      renderProps(props, {
        values: { ...state },
        input: id => {
          const value = state[id] || ''
          const setValue = value => setState({ [id]: value })

          return {
            bind: {
              onChange: event => setValue(event.target.value),
              value,
            },
            set: value => setState(s => ({ [id]: set(value, s.value) })),
            value,
          }
        },
        checkbox: id => {
          const checked = state[id] || ''
          const setValue = checked => setState({ [id]: checked })

          return {
            bind: {
              onChange: event => setValue(event.target.checked),
              checked,
            },
            set: checked => setState(s => ({ [id]: set(checked, s.checked) })),
            value,
          }
        }
      })
    }
  </State>
)

export default Form
```

**or even a breaking change**

```jsx
renderProps(props, {
  values: { ...state },
  // the difference between value and checked is just `event.target.value/checked`, so `select` use `value`
  value: id => {
    const value = state[id] || ''
    const setValue = value => setState({ [id]: value })

    return {
      bind: {
        onChange: event => setValue(event.target.value),
        value,
      },
      set: value => setState(s => ({ [id]: set(value, s.value) })),
      value,
    }
  },
  checked: id => {
    const checked = state[id] || ''
    const setValue = checked => setState({ [id]: checked })

    return {
      bind: {
        onChange: event => setValue(event.target.checked),
        checked,
      },
      set: checked => setState(s => ({ [id]: set(checked, s.checked) })),
      value,
    }
  }
})
```

**Comment by TrySound** [comment]
@xialvjun Rise an issue please

**Comment by guilhermedecampo** [comment]
@renatorib Scroll component would be super awesome.

**Comment by renatorib** [comment]
1.0.0 released
