### ISSUE TITLE
Integrating state container to react

### ISSUE THREAD

**Issue by TrySound** [renatorib/react-powerplug#62]
Today Dominic posted gist with some future ideas. I think you will be interested.

https://gist.github.com/trueadm/35f083d32e5af93dd8fd706dae378123

/cc @renatorib @souporserious

**Comment by renatorib** [comment]
Interesting.
I liked these factories... Particularly `React.createState(initialState)`.

This api will be implemented or are just "mind drafts"?
This `adopt` syntax is related to Async React?

**Comment by TrySound** [comment]
It's just ideas. But you may help with your opinions and suggestions.

`adopt` syntax is not related to async. It's just sugar for children as function. It can solve nesting problem like `async/await` does with promises.

`createState` is nice however I have a lot of cases with settings defaults from props. Probably `deriveState` can help here but in more verbose way.

**Comment by renatorib** [comment]
I saw that he keep working in this idea (& adopt) in this new gist https://gist.github.com/trueadm/17beb64288e30192f3aa29cad0218067

For now I'll close this issue just to clean up, but I'll keep my eyes on it! Maybe we can take some of their ideas and apis to powerplug!

I'm loving the fact that the react is implementing render props internally in their apis
