### ISSUE TITLE
Refactor components' `onChange` to match same `initial` type

### ISSUE THREAD

**Issue by renatorib** [renatorib/react-powerplug#70]
I find it very inconsistent that you pass `initial={boolean}` to `<Toggle>` and onChange fires with `{on: boolean}`.
I think onChange should call with the fundamental component's state

Toggle -> boolean (on)
Counter -> number (count)
Value -> any (value)
List -> array (list)
Hover -> boolean (isHovered)

Example:
```jsx
<Counter onChange={count => console.log(count)}>
 {/* ... */}
</Counter>
```

etc...

**Comment by TrySound** [comment]
@renatorib added test for all components except `Form`. Can you take care of it? And we could start working on this api change.

**Comment by renatorib** [comment]
Thanks @TrySound, these tests will help a lot!
Actually I already started to do but I did not pushed anything yet

**Comment by theKashey** [comment]
+1
This change should be made.
