### ISSUE TITLE
Documentation note about stable branch is not clear enough

### ISSUE THREAD

**Issue by jamescrstnwork** [renatorib/react-powerplug#84]
Toggle documentation has misleading property `set`, actually it is `setOn`

**Comment by TrySound** [comment]
@jamescrstnwork Documentation is right.

https://github.com/renatorib/react-powerplug#%EF%B8%8F-master-is-unstable

**Comment by jamescrstnwork** [comment]
@TrySound no its not, I tried , set method comes as undefined.
I looked into the code and changed it to `setOn` now it works.

**Comment by TrySound** [comment]
Okay, another link https://github.com/renatorib/react-powerplug/blob/master/package.json#L3

/cc @renatorib The message is still not clear.

**Comment by jamescrstnwork** [comment]
ohk, I got it.
Its in the stable branch 1.0 : [https://github.com/renatorib/react-powerplug/blob/0.1-stable/src/components/Toggle.js]

**Comment by renatorib** [comment]
I do not see how the message can be clearer. Unfortunately we will still have this problem until 1.0 is released.

If anyone has any suggestions on how to make the message clearer without taking the focus off the rest, feel free to send a PR!

Thanks!
