### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by theKashey** [renatorib/react-powerplug#86]
I know that supporting all type systems is a hard work, but without them life is not so sweet.

I am happy to make a PR, but you have to decide:
 - you are happy to ship d.ts along library, so lets add them here.
 - types is the right place for types, so please _definitely_ publish them.

I'll prefer the first way, but it is up to you.

**Comment by renatorib** [comment]
I use typescript in my job and I think of typing powerplug every day! The problem is that I have little time available, and I can only give attention to some issues / pr and work on a features for 1.0 rarely.
But it would be great to support typescript, including I would love to help with somebody's initial work. :smiley:

**Comment by theKashey** [comment]
@renatorib - that's I want to hear.
I already have to partially cover powerplug with typedef, so I'll just finish that move.
Porting from Flow to TS is a straightforward action.

**Comment by LinusU** [comment]
@renatorib 

> I use typescript in my job and I think of typing powerplug every day!

Would you be interested in porting the entire lib to be written in TS? I'd be happy to do it if it's desirable 🙌

**Comment by renatorib** [comment]
@LinusU I appreciate your disposition to help, I think personally I prefer typescript, but I do not think it's a good idea thinking about open source. I think it can close doors for other people who want to contribute... maybe flowtype could be a better idea, but I'm also resilient. 

What you think?

**Comment by LinusU** [comment]
> I think it can close doors for other people who want to contribute...

I can definitively see this argument. Personally, I think it's especially the overhead of having a build system at all. I usually write my packages in JavaScript and stick a definition file in them, just so that there is no barrier to working with the package. 

> maybe flowtype could be a better idea

I'm not sure why it would be better with flow? 🤔 

> What you think?

I don't have any strong feelings, I just offered my help since it sounded like you maybe would have preferred it ☺️ 

Absolutely no hard feelings if you don't want to do it ❤️

**Comment by TrySound** [comment]
Flow will require less code changes, less annotations and won't require renaming.

**Comment by theKashey** [comment]
- Library in JS -> have to write d.ts, may write .flow
- Library in Flow -> have to write d.ts
- Library in TS -> may write .fow

So TS has fewer borders and requirements.

**Comment by TrySound** [comment]
I don't get. What do you mean by "may"?

**Comment by theKashey** [comment]
Flow is fully functional without type definition for a library. But TS - not really.
You can always dropin some custom typings, spreading `any` unto it, but that does not always work.
In some conditions `any` could be converted to `{}`, not letting you to do anything, and you will have   to use `as any`, again, and again.

TS without right d.ts is a 💩, while Flow is 🍔.

You _MAY_ not ship Flow types, and nobody will complain.

**Comment by TrySound** [comment]
What will change if we will generated TS definitions from flow types?

**Comment by theKashey** [comment]
So, actually after I wrote that sentence, and I wrote it cos Gasby did it, I've tried to convert some by TS-only libraries to flow.
9 hours later it still does not work.

**Comment by TrySound** [comment]
What exactly doesn't work?

**Comment by theKashey** [comment]
Exact types, default exports, "React types" itself (they are not portable).
TS and Flow are 95% equal, but rest 5% could be a pain in the ass.

**Comment by TrySound** [comment]
I thought ts has exact types by default. React.Node -> `React.ReactNode`. What's else? ComponentType I see from your PR is the same.

Heh, default exports doesn't work. It's the problem of TS which can't work with esm/cjs interop and requires this legacy [s**t](https://github.com/jamiebuilds/create-react-context/pull/20/files).

**Comment by renatorib** [comment]
@LinusU 
> I'm not sure why it would be better with flow? 🤔

I think both are barriers to contributors, but I think typescript might scare you more than the flow. I mean, flow is just javascript with static types. Is less strict than typescript.

However, I'd rather leave code in javascript and keep typings separated. People can contribute without know flow/ts, and other people can add types. No closed doors.
