### ISSUE TITLE
onChange bubbling

### ISSUE THREAD

**Issue by theKashey** [renatorib/react-powerplug#89]
Having code:
```js
<Value>
{ ({value, set}) =>
  <Value onChange={set}>
  { ({set} ) =>...
 </Value>
}
</Value>
```
When I will call `set` on internal Value it will set that value, and call onChange handler.
onChange handler will be called with `{value}`, not `value`, as long onChange is a State property.

Result: value on topmost Value will be `{value}`.

Proposal: onChange on any component should emit `value` of that component unchanged. As it will be presented to the consumer.

**Comment by TrySound** [comment]
@theKashey Do you mean this one?
https://github.com/renatorib/react-powerplug/issues/70

**Comment by theKashey** [comment]
@TrySound, yeah. Duplicate.
