### ISSUE TITLE
What is the point is "Loading" component if we already have "Toggle"?

### ISSUE THREAD

**Issue by MaxGraey** [renatorib/react-powerplug#9]
**Toggle**
```jsx
const Toggle = ({ initial = false, ...props }) => (
  <State initial={{ on: initial }}>
    {({ state, setState }) => renderProps(props, {
      on: state.on,
      off: !state.on,
      toggle: () => setState(s => ({ on: !s.on })),
      setOn: (on) => setState({ on }),
    })}
  </State>
)
```

**Loading**
```jsx
const Loading = ({ initial = false, ...props }) => (
  <State initial={{ loading: initial }}>
    {({ state, setState }) => renderProps(props, {
      isLoading: state.loading,
      toggleLoading: () => setState(s => ({ loading: !s.loading })),
      setLoading: (loading) => setState({ loading }),
    })}
  </State>
)
```

The logic is the same except names

**Comment by renatorib** [comment]
Hey, Max! 

In fact, they do the same thing: turn a state on/off. 

I was thinking in "what the most common scenarios?" and found these two, and another ones. I decided to create both, so people can use it contextually. 

In the next major version that I'm working on (1.0), I'm planning to have only one, but using an alias to another, so I can remove "duplicate" code, but still have both.

Also I'm planning to add support to a babel plugin like lodash, so you'll put into your app bundle what you really use.

**Comment by renatorib** [comment]
Just for complementing
Value and Index also do the same thing, since Value also accept a number, you can do the same logic what you do with Index, using Value.

**Comment by MaxGraey** [comment]
@renatorib thanks for explanation. So in the next version we have more convenient approach.

**Comment by renatorib** [comment]
:)
